//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;	// For List<>
//***************************
//
//	A class to manage the weapons inventory
//	This will manage a List<> of equippables
//	Loading from and saving weapons and their
//	attributes to playerprefs will be managed here
//	 
//	The player will have a script WeaponHand and WeaponManager attached
//
//**************************

public class WeaponManager : MonoBehaviour
{
	[SerializeField]
	List<Equippable> unlockedWeapons;
	[SerializeField]
	List<Equippable> lockedWeapons;
	[SerializeField]
	public WeaponManager ()
	{

	}
	
	public void loadUnlockedWeapons(ref List<Equippable> e)
	{
		e = unlockedWeapons;
	}
	public void loadLockedWeapons(ref List<Equippable> e)
	{
		e = lockedWeapons;
	}
	public void setUpForPlay()
	{
		for (int i = 0; i < unlockedWeapons.Count; i++)
		{
			Debug.Log("ettingupWeapon");
			unlockedWeapons[i].setUpForPlay();
		}
	}
}

